spring:
  r2dbc:
    url: r2dbc:mysql://${MYSQL_HOSTNAME}:3306/emall
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}

server:
  address: 127.0.0.1
  port: 8080

oss:
  bucket-name: "yaojiabuy"
