spring:
  application:
    name: nightgrass
  r2dbc:
    url: r2dbc:mysql://localhost:3306/emall
    username: smallboy
    password: abcd1234
    pool:
      enabled: true
      initial-size: 5
      max-size: 20
